# https://github.com/marketplace/actions/deploy-pr-preview#usage
name: Deploy Docs PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    # executor: fake
    runs-on: ubuntu-20.04
    steps:
      # - checkout
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          echo "hello?"

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs/build/
